name: Update Next Scraping Date

on:
  schedule:
    - cron: '0 0 5 * *'  # Se ejecutará el 5° dia de cada mes a las 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # Agregar permisos explícitos

jobs:
  set_next_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          playwright install-deps  # Instalar dependencias del sistema

      - name: Obtener próxima fecha
        id: get_date
        run: |
          NEXT_DATE=$(python -c "from src.scraper import IndecScraper; print(IndecScraper().obtener_fecha_proximo_informe())")
          echo "NEXT_DATE=$NEXT_DATE" >> $GITHUB_ENV

      - name: Guardar fecha en archivo
        run: |
          echo "${{ env.NEXT_DATE }}" > next_date.txt
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add next_date.txt
          git commit -m "Actualizar fecha del próximo scraping: ${{ env.NEXT_DATE }}"
          git push
